### PR TITLE
Explicitly remove any finite rlimits when resetting the prover state.

### PR DESCRIPTION
**Pull request by parno**
This addresses Issue #366.

### CODE REVIEW

**Review by shazqadeer — APPROVED** [review]
I am approving this PR.  You might want to consider whether setting rlimit to 0 should be done before or after sending the reset command.  Perhaps doing a reset could exhaust  Z3's resources :-)

**Comment by parno** [comment]
Heh, I would hope reseting was free -- charging for a reset seems cruel :)

Do I need to do anything for this to merge?  I don't have permissions to do it myself.

**Comment by parno** [comment]
@shazqadeer Would you mind bumping Boogie's version number, so we can update Dafny to depend on a version that includes this change?  Thanks!

**Comment by shazqadeer** [comment]
Done.

**Comment by parno** [comment]
Thanks!

**Pull request merged**
