### PR TITLE
Documentation for encoding of control flow in VC generation

### PR DESCRIPTION
**Pull request by shazqadeer**

### CODE REVIEW

**Review by RustanLeino — APPROVED** [review]
Very helpful documentation, and a good scheme!

**Comment by shazqadeer** [comment]
@bkragl :  Do you understand why this build is failing?

**Comment by shazqadeer** [comment]
@keyboardDrummer :  The problem appears to be the one related to libraries on Ubuntu. Any suggestions?

**Comment by bkragl** [comment]
> @bkragl : Do you understand why this build is failing?

Nope, looks like an issue with GitVersion.

@keyboardDrummer also had to re-trigger a build in PR #319. Was that the same issue?

**Comment by keyboardDrummer** [comment]
> > @bkragl : Do you understand why this build is failing?
> 
> Nope, looks like an issue with GitVersion.
> 
> @keyboardDrummer also had to re-trigger a build in PR #319. Was that the same issue?

Yes that was the same issue. I guess we should revert all or a part of PR #319

**Comment by shazqadeer** [comment]
I am triggering a rebuild just to see if problem gets fixed deterministically with a rebuild.  I suppose we should try to get to the bottom of the problem.

**Comment by bkragl** [comment]
> I am triggering a rebuild just to see if problem gets fixed deterministically with a rebuild. I suppose we should try to get to the bottom of the problem.

Looks like it worked.

This was the error message in the failed build:

```
/home/travis/.nuget/packages/gitversiontask/5.5.1/build/GitVersionTask.targets(10,9): error : NameConflictException: failed to write reference 'refs/heads/pull/320/merge': a reference with that name already exists. [/home/travis/build/boogie-org/boogie/Source/UnitTests/TestUtil/TestUtil.csproj]
```

Note that for each PR there are actually 4 builds: {Branch, Pull Request} x {Debug, Release}
Only one of them failed.

I searched for the error and found https://github.com/GitTools/GitVersion/issues/864, where people also reported this problem happening sporadically on pull requests. Supposedly it was fixed in GitVersion 5.3.3.

It's a long shot, but we could try to call `dotnet build` explicitly before `dotnet pack`. If I remember correctly, there was a glitch in #319 that `dotnet pack` does not compile the unit tests, which is now done by `dotnet test`. Maybe compiling everything together works (because the error shows up for a test project).

**Pull request merged**
