### PR TITLE
Emit axioms only for types used in program

### LINKED ISSUE #660: Emit axioms only for theories used by queries
Currently, the SMT-Lib generated from Boogie includes background axioms for the built-in data types, even when they aren't used. In particular, this includes the `RegEx` type, which CVC5 doesn't support. By emitting axioms only for used theories, we could improve the ability to send a single SMT query to multiple solvers.

This would solve part of the issue encountered in the discussion of #659.

### PR DESCRIPTION
**Pull request by atomb**
Previously, Boogie would emit axioms for all types it supports, even if not used in the input program. This PR causes it to instead emit axioms only for the types that are used. This results in more compatible SMT-Lib files, usable by solvers that don't support theories such as regular expressions.

Fixes #660. Also addresses part of #659.

### CODE REVIEW

**Review by keyboardDrummer — APPROVED** [review]

**Review by MikaelMayer — APPROVED** [review]
Thanks. Although I'm not sure it will improve efficiency (which you don't claim anyway), having it to work with other SMT solvers is priceless.

**Comment by shazqadeer** [comment]
@atomb:

When I try to run the test UsedTypes.bpl on my machine (Mac), I get this error message:

```
$ "!" "grep" "RegEx" "/Users/shaz/Source/boogie/Test/prover/Output/UsedTypes.bpl.tmp.smt2"
# command stderr:
'!': command not found
error: command failed with exit status: 127
```

Do I have to install some other tool ?

**Comment by atomb** [comment]
Oh, interesting. It works correctly on my Mac. I'll look into whether there's a better way to require the absence of a match in a file.

**Comment by keyboardDrummer** [comment]
> Oh, interesting. It works correctly on my Mac. I'll look into whether there's a better way to require the absence of a match in a file.

Dafny has this line to introduce `!`: https://github.com/dafny-lang/dafny/blob/master/Test/lit.site.cfg#L178

But that's not in https://github.com/boogie-org/boogie/blob/master/Test/lit.site.cfg

**Comment by atomb** [comment]
> > Oh, interesting. It works correctly on my Mac. I'll look into whether there's a better way to require the absence of a match in a file.
> 
> Dafny has this line to introduce `!`: https://github.com/dafny-lang/dafny/blob/master/Test/lit.site.cfg#L178
> 
> But that's not in https://github.com/boogie-org/boogie/blob/master/Test/lit.site.cfg

Strange, given that I wasn't using Dafny's configuration to run this test. Regardless, the test uses a more standard approach now.

**Pull request merged**
