### PR TITLE
Enabling string operations.

### PR DESCRIPTION
**Pull request by michael-emmi**
This PR adds native `string` and `regex` types, along with string literals, so that [Z3 string reasoning](https://rise4fun.com/z3/tutorialcontent/sequences#h21) can be leveraged at the Boogie level.

As an example, this allows verification of the following program.
```
procedure main() {
    var s: string;
    s := "a";
    assert in(concat(s,s), star(s2re(s)));
}

function {:builtin "str.in.re"} in(string, regex): bool;
function {:builtin "str.++"} concat(string, string): string;
function {:builtin "re.*"} star(regex): regex;
function {:builtin "str.to.re"} s2re(string): regex;
```

### CODE REVIEW

**Comment by shazqadeer** [comment]
@RustanLeino, @zvonimir : Shall we move ahead with this PR?

**Comment by zvonimir** [comment]
@michael-emmi is this ready to be merged?

**Comment by michael-emmi** [comment]
From my side, yes.

**Comment by zvonimir** [comment]
When we were implementing support for floating-points, @RustanLeino had some great suggestions for improvements. So it would be great if @RustanLeino could quickly review this pull request.

**Comment by zvonimir** [comment]
@RustanLeino Now that there has been a flurry of activities around Boogie, it would be awesome if you could quickly review this pull request too. Thx!

**Comment by shazqadeer** [comment]
I have merged this PR since it has been waiting for a long time.  I am sure we will continue to improve support for string operations and @RustanLeino can provide feedback at that time.  I hope this was not the final word on strings!  Great work, @michael-emmi .

**Pull request merged**
