### PR TITLE
Removed function renaming in model parsing

### PR DESCRIPTION
**Pull request by shazqadeer**
Resolves PR #417 which should be discarded.

### CODE REVIEW

**Comment by shazqadeer** [comment]
FYI: @Dargones

**Comment by Dargones** [comment]
Just checked and this fixes the issue that I was having, thank you, @shazqadeer ! I do believe this will necessitate a fix to Dafny [here](https://github.com/dafny-lang/dafny/blob/0fa9f99df7d91bc059b63f2d39c44baca958ba67/Source/DafnyServer/boogie/DafnyProvider.cs#L47-L48) but I will be working on that file anyway.

**Review by zvonimir — APPROVED** [review]
Looks good to me.

**Comment by zvonimir** [comment]
Thanks @shazqadeer! This just unblocked us.

**Pull request merged**
