### PR TITLE
Update to .NET 5.0

### LINKED ISSUE #402: Boogie on .NET 5.0 ?
I couldn't find a duplicate of this, though I figure it has been asked before.  Currently, it seems like you need `dotnet-runtime-3.1` to run Boogie on Linux.  Otherwise, you end up with an error message like this:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.7 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

It seems to me that modern Linux distro's support .NET 5.0 and it seems to generally be the default choice.  So, I'm always either manually installing `dotnet-runtime-3.1` or asking someone to do it for me.  Anyway, I don't know what the trade-offs are here.

### PR DESCRIPTION
**Pull request by bkragl**
Closes  #402

### CODE REVIEW

**Review by shazqadeer — APPROVED** [review]

**Comment by shazqadeer** [comment]
Does the Boogie upgrade to 5.0 mean that Dafny will have to be upgraded to 5.0?

**Comment by bkragl** [comment]
> Does the Boogie upgrade to 5.0 mean that Dafny will have to be upgraded to 5.0?

Dafny is already on .NET 5.0.

**Comment by shazqadeer** [comment]
@akashlal :  Any concerns?

**Comment by akashlal** [comment]
Sounds good to me. No concerns.

**Comment by zvonimir** [comment]
Is Corral going to switch too? Or maybe it already did? @akashlal? Thx!

**Comment by akashlal** [comment]
@zvonimir Corral hasn't switched yet, but we should do it after boogie moves.

**Comment by shazqadeer** [comment]
@bkragl :  Merge?

**Pull request merged**
