### PR TITLE
Remove labels and unused VC generation code

### PR DESCRIPTION
**Pull request by shazqadeer**
This PR removes labels inside the verification conditions generated by Boogie.  Labels were used to generate error traces but are obsolete now given that SMT solvers are reasonably good at generating models.  The new mechanism uses extra "control-flow" instrumentation in the verification to generate error traces.  This PR also removes a bunch of algorithms for generating verification conditions that were not being used. As a result, the option /vc has been eliminated.

The tests inside stratifiedInline and extractLoops folder have been disabled because they are dependent on implementation of stratified inlining which is going to be eliminated from Boogie (#200) and which works only with labels.

The option MULTI_TRACES worked only with labels.  It is now obsolete and has been eliminated.  If there is demand for multiple error traces, we can investigate techniques based purely on model finding to solve the problem.

### CODE REVIEW

**Comment by akashlal** [comment]
Changes look good. Goodbye labels.

**Comment by shazqadeer** [comment]
@RustanLeino : I double checked that with the current version of this branch, all tests in Dafny pass (with Z3 4.8.4) except those in comp folder and a couple others that require some .net dlls to be installed (I am working on a MacOS machine).  So I think we are good to land this PR.

**Comment by shazqadeer** [comment]
I have removed /vc option entirely.  So its mention in the help message is also eliminated.

I have removed the doomed code and tests.

I tried to remove `doomedInjectedAssumptionVariables` in a couple of different ways (without really understanding the point of this variable) but the test Test/snapshots/runtest.snapshot was failing.  So I gave up on this endeavor. Perhaps @RustanLeino  can explain the purpose of this field and whether it can be eliminated.  If it cannot be eliminated, perhaps it should be renamed.

**Comment by wuestholz** [comment]
@shazqadeer @bkragl `doomedInjectedAssumptionVariables` definitely doesn't have anything to do with the doomed VC generation option. I wrote that code a long time ago for the verification result caching feature that is used by the Dafny IDE, but I don't fully remember the reason for picking that name... Probably that any attempt at reusing cached results is doomed. :)

**Comment by RustanLeino** [comment]
I'm joining the party only after it already ended.

@shazqadeer Yes, this looks good. Thanks for doing this spring cleaning.

I'm surprised about the deletion of stratified inlining. Doesn't Corral use it?

@bkragl A _doomed program point_ is one from which execution will inevitably fail, regardless of how control reached the doomed point. It was the subject of @martinschaef's PhD thesis.

**Pull request merged**
