### PR TITLE
Updated Z3 to version 4.11.2

### PR DESCRIPTION
**Pull request by rakamaric**
Attempting to update Z3 to its latest release.

### CODE REVIEW

**Comment by rakamaric** [comment]
Ok, several tests are failing.
@shazqadeer could you take a look at the CIVL one maybe? Thanks!
Let's maybe address the others one by one.

**Comment by shazqadeer** [comment]
@rakamaric : I can't seem to find the MacOS binary for Z3 4.11.2. Any pointers?

**Comment by rakamaric** [comment]
> @rakamaric : I can't seem to find the MacOS binary for Z3 4.11.2. Any pointers?

If you are running an Intel-based Mac like me:
https://github.com/Z3Prover/z3/releases/download/z3-4.11.2/z3-4.11.2-x64-osx-10.16.zip

There is another one for the new ARM-based ones too.

**Comment by shazqadeer** [comment]
I put up a PR to address the Civl test.

**Review by shazqadeer — APPROVED** [review]

**Pull request merged**
